### ISSUE TITLE
Set up viz branch deployment CI

### ISSUE THREAD

**Issue by AntoineDao** [pollination/annual-daylight#105]
As per [Mostapha's post](https://3.basecamp.com/4298486/buckets/17169066/messages/4304826018) we want to set up a demo CI process to deploy separate recipes with a special `viz` tag.

**Comment by AntoineDao** [comment]
I have to re-open this issue because of [conflict issues](https://github.com/pollination/annual-daylight/runs/4067823087?check_suite_focus=true#step:6:25) running the `git rebase` command in CI.

This is super weird though because I don't run into that issue when running `git rebase` on my local machine... @mostaphaRoudsari is there a case to be made to simply set up the `viz` as a separate recipe? It could exist in the same repository but in a different folder and then be deployed in parallel to the "normal" recipe.

**Comment by mostaphaRoudsari** [comment]
I got the push to staging to work by using `extras_require` key. Here is the successful action: https://github.com/pollination/annual-daylight/actions/runs/1474804385

But it still fails for pushing to production because the get-context step fails to return the tag: https://github.com/pollination/annual-daylight/runs/4246942083?check_suite_focus=true#step:4:1

![image](https://user-images.githubusercontent.com/2915573/142351514-51645daf-b8b8-4f60-8902-2d3381d1ec50.png)

If we can fix this step then everything should work with the new set-up and we shouldn't have issues with `git rebase`. Hopefully that's an easy one to fix.

**Comment by tymokvo** [comment]
`get-context` is not setting the output correctly https://github.com/pollination/annual-daylight/runs/4246942083?check_suite_focus=true#step:4:7

**Comment by mostaphaRoudsari** [comment]
Resolved via https://github.com/pollination/annual-daylight/commit/0dfadec2d0d1c07799c3dea39adef8b95e186de1! Thanks, @tymokvo.
